# Generated by Django 3.1.5 on 2021-01-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
