# Generated by Django 3.1.5 on 2021-09-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporty', '0003_auto_20210904_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='match',
            field=models.IntegerField(),
        ),
    ]
